import math
from pathlib import Path
import pandas as pd
import subprocess

configfile: 'config.yml'

# This code validates and processes the configuration and sets global variables:
include: 'steps/setup.smk'

# List short steps here so they will not be submitted as cluster jobs:
# (These can be specified on a per-file basis)
localrules:
    # index_bed,

# These are the target files to be generated (or regenerated if outdated).
# By default it includes all output files specified in the config file.
rule all:
    input:
        outputs,
        # expand(interm_dir / 'covar' / '{pheno}.covar.tsv', pheno=phenotypes.keys()),

include: 'steps/covariates.smk'
for analysis in analyses:
    include: f'steps/{analysis}.smk'
